leam-tech/renovation_core

renovation_core/app.py, renovation_core/commands/__init__.py, renovation_core/install/benchconfig.py
- Added Procfile manipulation
- Added “serve” command part of renovaiton group
- Added serve function that uses renovation_core.app instead of frappe.app to handle JWT authorized sessions
=> fix: bench start when renovation_core is installed

renovation_core/client.py
Frappe supplies LDAP details to the login page while rendering it
There is no whitelisted API for this, hence this helps for ldap login in lts-renovation
=> cmd: get_ldap_client_settings

renovation_core/app.py
Frappe sites in production were failing without this
=> fix: frappe.app missing imports

renovation_core/utils/auth.py
Since SMS settings may modify the number by either adding or removing a `+`, the check for the return of SMS (list) against the request's mobile number, it will be false. That's why we can check the number partially (last 5 digits).
=> fix: Mobile number compared after being modified

renovation_core/utils/logging.py
This particular bug was noticed on Sezer
```
[2020-06-02 02:27:15 +0000] [3816] [ERROR] Error handling request /
Traceback (most recent call last):
File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
self.handle_request(listener, req, client, addr)
File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
respiter = self.wsgi(environ, resp.start_response)
File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/werkzeug/local.py", line 231, in application
return ClosingIterator(app(environ, start_response), self.cleanup)
File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/werkzeug/wrappers/base_request.py", line 237, in application
resp = f(*args[:-2] …
```
=> fix: Null Exception

renovation_core/utils/forgot_pwd.py
a function with `update_password` exists in the same py module.
To actually update the password, the `update_password` in `frappe.utils.password` has to be used,
=> fix: pwd-reset bug

renovation_core/utils/auth.py
The response-obj was missed out at the end
=> fix: response of verify_otp_deprecated is empty

renovation_core/hooks.py, renovation_core/oauth.py, renovation_core/tasks.py
Introduction of the ability to login and/or create a user using Google.
Below are the fields required in the root `common_site_config.json` for Signing in with Apple
"apple_login_native":{
"client_id": "......",
"client_secret":"......"
},
"apple_login_web":{
"client_id": "......",
"client_secret":"......",
"web_url":"https://example.com"
},
"apple_login_android":{
"client_id": "......",
"client_secret":"......",
"android_url": "<site>/api/method/renovation_core.oauth.redirect_apple_login_to_android",
"android_package_id":"com.example.com"
},
"apple_keys": {
"iss": "......",
"kid": "......",
"private_key": "-----BEGIN PRIVATE KEY-----......-----END PRIVATE KEY-----"
}
=> feat: OAuth2 using Google & Apple

renovation_core/oauth.py
This feature allows to override the redirect URL which is set to the site itself by default.
This can be useful, if the Google OAuth flow should end in a frontend site.
Override the redirect URL by adding key in `common_site_config.json` as below:
```json
{
"google_redirect_url": "https://example.com"
}
```
=> feat: Optionally specify redirect URL for Google

renovation_core/renovation_core/doctype/renovation_docfield/renovation_docfield.py
This will fix the error that we get when installing renovation_core on frappe-v13-beta
=> fix: Duplicate RDocfields on migration

renovation_core/__init__.py
Looks like `on_login` hook is triggered before session is created
=> fix: QuickLoginPin cache key

renovation_core/renovation_dashboard_def/doctype/renovation_dashboard/renovation_dashboard.py
The docfield `is_standard` in RenovationDashboard doctype is a `Select` field with options Yes/No
The frappe function `export_module_json` takes in a boolean for it's `is_standard` param.
=> fix: RenovationDashboard is_standard flag

renovation_core/renovation_core/doctype/guest_chat_user/guest_chat_user.js, renovation_core/renovation_core/doctype/guest_chat_user/guest_chat_user.json, renovation_core/renovation_core/doctype/guest_chat_user/guest_chat_user.py, renovation_core/renovation_core/doctype/guest_chat_user/test_guest_chat_user.py, renovation_core/utils/chats.py
`Chat Token` is a frappe doctype used for chatting with Guest (non-logged) users.
`Guest Chat User` extends `Chat Token` with more fields like name, email, mobile_no.
Took the doctype approach instead of CustomField on ChatToken as suggested by @MalikZu 
The endpoint `renovation_core.utils.chats.get_guest_token` creates both Chat Token and Guest Chat User doc.
=> feat: Guest Chat User

renovation_core/patches.txt, renovation_core/patches/v1_1/delete_duplicate_fcm_tokens.py, renovation_core/utils/fcm.py
This will strip away FCM tokens from old users when the same token gets registered against a new user
=> fix: Duplicate User FCMs

renovation_core/__init__.py, renovation_core/auth.py, renovation_core/utils/auth.py, renovation_core/utils/files.py
This PR aims to make use of the frappe's OAuth flow for auth tokens.
- Change `jwttoken` to `Bearer` in request headers (for compatibility with existing app)
- Supports SMS / PIN Logins that has `use_jwt` flag
- Updated functions that makes use of old tokens
Please check out the notion doc
=> fix: frappe-v13 jwt

renovation_core/realtime.py, socketio.js
Socket.io was failing to connect when the authorization header contained access_token. This is because of the previous implementation of JWTToken in which a JWT token was decoded to extract the user which is not the case anymore.
The solution lies in two places:
socketio.js => Replace the authorization header type from JWTToken -> Bearer
realtime.py => Remove JWT decoding and validate using frappe's validate_auth if token is passed, otherwise set the user in frappe.session.user
=> fix: Handle access_token with socket.io

renovation_core/app.py
For private files, our way to go with jwt tokens was to have it appended in the query string:
```
https://test-site.leam.ae/api/private/files/private_file.pdf?token=< TOKEN >
```
But after our recent migration of jwt to Oauth, this failed.
=> fix: Check OAuth for /private files

renovation_core/utils/sync.py
Fixes the blank /app screen in frappe.
This function is monkey patched just for `renovation_dashboard`. I think we could sync the same via `after_migrate` hook ?
=> fix: Workspaces

renovation_core/db/db_query.py, renovation_core/db/query.py
The overriden `execute` method of `DatabaseQuery` has the param `query` which is not used by the app. In addition, the base method `execute` no longer has `query` as a param. To solve this:
- Removed `query` as a param to the `UpdatedDBQuery` and consequently passing it to the base method.
- Removed `None` as the first argument of its usage.
=> fix: Remove unused param "query" in execute

renovation_core/hooks.py, renovation_core/utils/images.py
This PR makes 2 changes related to "Renovation Image Settings": 
1. Adds the `on_update` File doc_event to `hooks.py`, so that  "Auto Convert Thumbnails" and "Auto apply watermarks" settings work properly as intended i.e: Every image file uploaded to the site will generate thumbnails or have watermarks applied depending on the settings selected.
2. Adds a helper method to easily retrieve the thumbnail URL of an image given information about the Doc it exists on.
=> feat: Enable watermarking and thumbnails and add helper methods

renovation_core/utils/auth.py
Priority of language set (frappe.local.lang) in [generate_otp](https://github.com/leam-tech/renovation_core/blob/e66ec1c3863ccffaa65d2582e7eadc06f837c54b/renovation_core/utils/auth.py#L17):
1. `lang` kwarg
2. `Accept-Language` header or from `frappe.session.user` (done by **frappe** )
3. is `user` exists from `medium_id` (_email_ or _mobile_) ie `user.lang` (ie **Guest Users**)
=> refactor: priority of language set by generate_otp

renovation_core/renovation_core/doctype/broadcast_message/broadcast_message.py
Newer versions of frappe require methods that are used by the UI using `runserverjob` to be whitelisted. Since the `send` method of Broadcast Message is not whitelisted, _Permission_ error is thrown.
Whitelist the method for logged in users.
=> fix(Broadcast Message): Whitelist send method

docs/setting-up.md
When running the command from the bench root, path needs to include `apps`
=> doc: correct path in line 11

renovation_graphql/__init__.py, renovation_graphql/http.py
We do not have a frappe_app attached to renovation_graphql, so I thought why don't we take a go at `Error Log` itself
- Passwords are masked
- Operation Name are obtained from query
=> [PMS-T-85] fix: GQL Errors in Error Log

renovation/tests.py
Solves an issue where changing user during testing would also overwrite TESTER_USER.
=> fix: explicitly cast `user` to string before saving as TESTER_USER
